In [26]:
import pandas as pd
import numpy as np

In [27]:
asian = pd.read_csv('asian_pop_id.csv')
asian = asian[["ID","2010"]]
asian.columns = ["ID","2010 Asian Pop"]
# asian

In [28]:
white = pd.read_csv('white_pop_id.csv')
white = white[["ID","2010"]]
white.columns = ["ID","2010 White Pop"]
# white

In [29]:
other = pd.read_csv('other_pop_id.csv')
other = other[["ID","2010"]]
other.columns = ["ID","2010 Other Pop"]
# other

In [30]:
black = pd.read_csv('black_pop_id.csv')
black = black[["ID","2010"]]
black.columns = ["ID","2010 Black Pop"]
# black

In [31]:
hispanic = pd.read_csv('hispanic_pop_id.csv')
hispanic = hispanic[["ID","2010"]]
hispanic.columns = ["ID","2010 Hispanic Pop"]
# hispanic

In [32]:
race = asian.merge(white,on='ID').merge(other,on='ID').merge(black,on='ID').merge(hispanic,on='ID')

In [33]:
race

,ID,2010 Asian Pop,2010 White Pop,2010 Other Pop,2010 Black Pop,2010 Hispanic Pop
0,1,"3,523","21,618","1,956","14,461","13,433"
1,2,"16,184","30,706","2,336","8,015","14,701"
2,3,"6,414","29,098","1,566","11,275","8,009"
3,4,"4,399","24,916","1,128","1,488","7,562"
4,5,"1,449","24,634",716,738,"4,330"
5,6,"5,653","75,845","2,021","3,651","7,198"
6,7,"3,296","53,138","1,358","2,753","3,571"
7,8,"8,140","58,033","1,605","8,732","3,974"
8,9,269,"9,885",132,29,872
9,10,"1,696","30,157",564,164,"4,442"
10,11,"2,256","17,475",525,265,"4,927"
11,12,"1,989","13,815",441,137,"2,126"
12,13,"4,600","8,847",687,573,"3,224"
13,14,"7,430","15,054","1,495","2,076","25,487"
14,15,"2,972","34,329","1,106",856,"24,861"
15,16,"3,736","22,234","1,321","1,736","24,332"
16,17,"1,587","29,512",528,308,"9,997"
17,18,377,"5,041",162,598,"7,248"
18,19,"1,537","11,959",653,"2,493","62,101"
19,20,294,"1,913",186,757,"21,860"
20,21,"1,194","11,166",616,991,"25,295"
21,22,"1,828","28,514","1,254","3,900","37,295"
22,23,222,"2,502",523,"23,030","30,046"
23,24,"3,106","47,051","1,774","6,404","23,901"
24,25,573,"4,364","1,018","83,837","8,722"
25,26,8,133,197,"17,315",348
26,27,83,698,240,"18,696",850
27,28,"8,022","23,042","1,466","17,303","5,048"
28,29,74,492,367,"32,835","2,144"
29,30,113,"3,056",288,"10,374","65,457"
...,...,...,...,...,...,...
47,48,26,126,194,"12,897",569
48,49,27,188,499,"43,447",458
49,50,5,522,105,"6,122",571
50,51,18,725,203,"9,354","4,809"
51,52,53,"3,969",167,777,"18,076"
52,53,14,166,369,"27,593","1,509"
53,54,2,32,65,"6,251",132
54,55,48,"4,235",108,364,"4,671"
55,56,346,"18,372",240,"2,040","13,515"
56,57,138,"2,874",69,130,"10,182"
57,58,"2,252","3,682",199,542,"38,693"
58,59,"2,445","2,667",155,234,"10,111"
59,60,"11,038","11,225",415,672,"8,627"
60,61,727,"4,697",374,"13,148","25,431"
61,62,222,"3,250",68,255,"14,314"
62,63,121,"1,892",131,"2,161","35,589"
63,64,212,"11,921",240,282,"10,484"
64,65,210,"4,924",162,"1,390","26,669"
65,66,190,"2,419",475,"27,403","25,141"
66,67,19,130,404,"34,178",774
67,68,34,105,343,"29,847",325
68,69,21,180,423,"31,590",388
69,70,276,"6,251",446,"18,976","15,132"
70,71,33,134,456,"47,661",459
71,72,112,"11,785",384,"6,838",915
72,73,12,121,309,"25,793",258
73,74,126,"16,413",185,987,"1,382"
74,75,92,"6,473",321,"15,039",619
75,76,"1,058","9,845",238,403,"1,212"
76,77,"6,582","30,889","1,628","8,104","9,318"

In [35]:
race.to_csv('race_2010_master.csv',index=False)